[workspace]
authors = [""]
channels = ["conda-forge"]
name = "RVSS_Need4Speed"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=1.26.4,<2"
scipy = ">=1.15.2,<2"
pytorch = ">=2.9.1,<3"
scikit-learn = ">=1.7.2,<2"
ipython = ">=8.37.0,<9"
scikit-image = ">=0.20.0,<0.21"
matplotlib = ">=3.10.8,<4"
tqdm = ">=4.67.1,<5"
roboticstoolbox-python = ">=1.1.1,<2"
git = ">=2.52.0,<3"
ipykernel = ">=7.1.0,<8"
mediapy = ">=1.2.4,<2"
py-opencv = ">=4.12.0,<5"
seaborn = ">=0.13.2,<0.14"
gym = ">=0.26.1,<0.27"
jupyter = ">=1.1.1,<2"
spatialmath-python = ">=1.1.15,<2"
machinevision-toolbox-python = ">=1.0.0,<2"
ipywidgets = ">=8.1.8,<9"
plotly = ">=6.5.0,<7"
torchvision = ">=0.24.1,<0.25"
conda-pack = ">=0.8.1,<0.9"
tensorboardx = ">=2.6.2.2,<3"
pynput = ">=1.8.1,<2"
click = ">=8.3.1,<9"
ipympl = ">=0.9.8,<0.10"
